# Model configurations for Depth Anything V3

# Model architecture configurations similar to DA3 config files
MODEL_CONFIGS = {
    'da3-small': {
        'encoder': 'vits',
        'features': 64,
        'out_channels': [48, 96, 192, 384],
        'dim_in': 768,
        'out_layers': [5, 7, 9, 11],
        'cat_token': True,
        'alt_start': 4,
        'qknorm_start': 4,
        'rope_start': 4,
        'has_cam': True,
        'is_nested': False,
        'is_mono': False,
    },
    'da3-base': {
        'encoder': 'vitb',
        'features': 128,
        'out_channels': [96, 192, 384, 768],
        'dim_in': 1536,
        'out_layers': [5, 7, 9, 11],
        'cat_token': True,
        'alt_start': 4,
        'qknorm_start': 4,
        'rope_start': 4,
        'has_cam': True,
        'is_nested': False,
        'is_mono': False,
    },
    'da3-large': {
        'encoder': 'vitl',
        'features': 256,
        'out_channels': [256, 512, 1024, 1024],
        'dim_in': 2048,
        'out_layers': [11, 15, 19, 23],
        'cat_token': True,
        'alt_start': 8,
        'qknorm_start': 8,
        'rope_start': 8,
        'has_cam': True,
        'is_nested': False,
        'is_mono': False,
    },
    'da3-giant': {
        'encoder': 'vitg',
        'features': 384,
        'out_channels': [1536, 1536, 1536, 1536],
        'dim_in': 1536,
        'out_layers': [9, 19, 29, 39],
        'cat_token': True,
        'alt_start': -1,
        'qknorm_start': -1,
        'rope_start': -1,
        'has_cam': True,
        'is_nested': False,
        'is_mono': False,
    },
    'da3mono-large': {
        'encoder': 'vitl',
        'features': 256,
        'out_channels': [256, 512, 1024, 1024],
        'dim_in': 1024,
        'out_layers': [4, 11, 17, 23],
        'has_cam': False,
        'is_nested': False,
        'is_mono': True,
    },
    'da3metric-large': {
        'encoder': 'vitl',
        'features': 256,
        'out_channels': [256, 512, 1024, 1024],
        'dim_in': 1024,
        'out_layers': [4, 11, 17, 23],
        'has_cam': False,
        'is_nested': False,
        'is_mono': True,
        'is_metric': True,
    },
    'da3nested-giant-large': {
        'encoder': 'vitg',
        'features': 384,
        'out_channels': [1536, 1536, 1536, 1536],
        'dim_in': 1536,
        'out_layers': [9, 19, 29, 39],
        'has_cam': True,
        'is_nested': True,
        'is_mono': False,
    },
}

# HuggingFace model repositories
MODEL_REPOS = {
    'da3_small.safetensors': 'depth-anything/DA3-SMALL',
    'da3_base.safetensors': 'depth-anything/DA3-BASE',
    'da3_large.safetensors': 'depth-anything/DA3-LARGE',
    'da3_giant.safetensors': 'depth-anything/DA3-GIANT',
    'da3mono_large.safetensors': 'depth-anything/DA3MONO-LARGE',
    'da3metric_large.safetensors': 'depth-anything/DA3METRIC-LARGE',
    'da3nested_giant_large.safetensors': 'depth-anything/DA3NESTED-GIANT-LARGE',
}
